# This file was generated by scripts/generate-homebrew-cask.sh. The tap PR
# is still opened by hand, see docs/RELEASE.md's "Updating the Homebrew
# Cask" section.
cask "careerrat" do
  version "0.16.0"
  sha256 "219823c590fcd543801c932314f9137ff5bd0cd395e4a5e94bf434a4b0abb217"

  url "https://github.com/CodesWhat/careerrat/releases/download/v#{version}/CareerRat-#{version}-arm64.dmg"
  name "CareerRat"
  desc "Local, offline-first job-search workspace"
  homepage "https://careerrat.com/"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on arch: :arm64
  # Matches LSMinimumSystemVersion baked into the app by electron-builder.
  depends_on macos: :monterey

  app "CareerRat.app"

  uninstall quit: "com.codeswhat.careerrat"

  # The packaged app sets CAREERRAT_HOME to <userData>/data, so the whole job
  # search (tracker, candidate profile, artifacts) lives under the first path
  # here. Only `brew uninstall --zap` touches it; a plain uninstall leaves it.
  zap trash: [
    "~/Library/Application Support/CareerRat",
    "~/Library/Preferences/com.codeswhat.careerrat.plist",
  ]

  caveats <<~EOS
    CareerRat is arm64-only today. There is no Intel build.
    This cask installs the desktop app only. The npm CLI is a separate install.
  EOS
end
