# This file was generated by idlescreen. DO NOT EDIT.
cask "idlescreen" do
  version "0.1.0,62"
  sha256 "7da786b0ba5e5a900c14d388282c73f99f43ecabffe3ceec6c57203ce5fe4ae5"

  url "https://github.com/CodesWhat/idlescreen/releases/download/v#{version.csv.first}/idlescreen-#{version.csv.first}-build#{version.csv.second}.dmg"
  name "idlescreen"
  desc "Metal-rendered ASCII art screen saver"
  homepage "https://github.com/CodesWhat/idlescreen"

  depends_on macos: :tahoe

  app "IdleScreen.app"

  uninstall quit: "com.idlescreen.app"

  zap trash: [
    "~/Library/Application Support/Idlescreen",
    "~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Idlescreen",
    "~/Library/Group Containers/group.com.idlescreen.shared",
    "~/Library/Preferences/com.idlescreen.app.plist",
    "~/Library/Saved Application State/com.idlescreen.app.savedState",
  ]

  caveats <<~EOS
    Open idlescreen once after installation, then enable it in System Settings > Wallpaper > Screen Saver.
    Camera access is requested only if you enable a camera-based effect.
  EOS
end
