# This file was generated by idlescreen. DO NOT EDIT.
cask "idlescreen" do
  version "0.1.2,64"
  sha256 "2e5ebbf222a060bba900baa7738c87bf4df58b7c9648b4885ab3ff5b78c7e687"

  url "https://github.com/CodesWhat/idlescreen/releases/download/v#{version.csv.first}/idlescreen-#{version.csv.first}-build#{version.csv.second}.dmg"
  name "idlescreen"
  desc "Metal-rendered ASCII art screen saver"
  homepage "https://github.com/CodesWhat/idlescreen"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on macos: :tahoe

  app "IdleScreen.app", target: "idlescreen.app"

  uninstall quit: "com.idlescreen.app"

  zap trash: [
    "~/Library/Application Support/Idlescreen",
    "~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Idlescreen",
    "~/Library/Group Containers/group.com.idlescreen.shared",
    "~/Library/Preferences/com.idlescreen.app.plist",
    "~/Library/Saved Application State/com.idlescreen.app.savedState",
  ]

  caveats <<~EOS
    Open idlescreen once after installation, then enable it in System Settings > Wallpaper > Screen Saver.
    Camera access is requested only if you enable a camera-based effect.
  EOS
end
