# This file was generated by GoReleaser. DO NOT EDIT.
cask "portwing" do
  version "0.9.19"

  on_macos do
    on_intel do
      sha256 "cea767e79de59e56d69530b839f326161280de67017ec116ec36ae662aee4477"
      url "https://github.com/CodesWhat/portwing/releases/download/v#{version}/portwing_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6743e1f0bc49cf255f64fec81b3221cd230c4f9e8576b5ab70647500b89f07e0"
      url "https://github.com/CodesWhat/portwing/releases/download/v#{version}/portwing_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "90ecfe1042ebf2c8303e8056784314fcf5dfb4f01612cede295349db25cf99da"
      url "https://github.com/CodesWhat/portwing/releases/download/v#{version}/portwing_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "edd961bac1aaab42e4a6b7bfa90c03da3ca63cf67a26607a05dba52e7b4ee323"
      url "https://github.com/CodesWhat/portwing/releases/download/v#{version}/portwing_#{version}_linux_arm64.tar.gz"
    end
  end

  name "portwing"
  desc "Security-first remote Docker agent for Drydock and standalone API clients"
  homepage "https://portwing.codeswhat.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portwing"

  # No zap stanza required

  caveats <<~EOS
    Portwing needs access to a Docker socket and authentication configuration.
    See https://portwing.codeswhat.com/docs/installation before starting it.
  EOS
end
