# This file was generated by GoReleaser. DO NOT EDIT.
cask "portwing" do
  version "0.9.7"

  on_macos do
    on_intel do
      sha256 "d3b0b24cc94ba3e0c08621b59634ee82d6df09019fd090925d02273690c82bf9"
      url "https://github.com/CodesWhat/portwing/releases/download/v#{version}/portwing_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "951e2b21dfa8c7706d295f790edf99d17ed2dfd594b0bb82bedce161e234224c"
      url "https://github.com/CodesWhat/portwing/releases/download/v#{version}/portwing_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "34c7f4941ed842acda68dcb41d51dd64cf80c14c75f0e867f2ec65d407755a91"
      url "https://github.com/CodesWhat/portwing/releases/download/v#{version}/portwing_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "91103d991bea88f8cef18b79ca65036cd87eca1e277de588f047d69bced2a9ae"
      url "https://github.com/CodesWhat/portwing/releases/download/v#{version}/portwing_#{version}_linux_arm64.tar.gz"
    end
  end

  name "portwing"
  desc "Security-first remote Docker agent for Drydock and standalone API clients"
  homepage "https://portwing.codeswhat.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portwing"

  # No zap stanza required

  caveats <<~EOS
    Portwing needs access to a Docker socket and authentication configuration.
    See https://portwing.codeswhat.com/docs/installation before starting it.
  EOS
end
