# This file was generated by GoReleaser. DO NOT EDIT.
cask "portwing" do
  version "0.9.9"

  on_macos do
    on_intel do
      sha256 "09e558b49d5ce0ead0ec06ff16f7b79b16dbd665dc799a9d9067c9b9e62c82d2"
      url "https://github.com/CodesWhat/portwing/releases/download/v#{version}/portwing_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dc812741ba5df9541523fd02d9f3bc283f289881dc25908128f44b4e28c7f68d"
      url "https://github.com/CodesWhat/portwing/releases/download/v#{version}/portwing_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "976de807a6639bc2bc62524227f9f1c1546a750cb31fe4ef602456b41c258e81"
      url "https://github.com/CodesWhat/portwing/releases/download/v#{version}/portwing_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce5700415f99be4c651656de92c353c019cee79927198223d0ca90decb89267c"
      url "https://github.com/CodesWhat/portwing/releases/download/v#{version}/portwing_#{version}_linux_arm64.tar.gz"
    end
  end

  name "portwing"
  desc "Security-first remote Docker agent for Drydock and standalone API clients"
  homepage "https://portwing.codeswhat.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portwing"

  # No zap stanza required

  caveats <<~EOS
    Portwing needs access to a Docker socket and authentication configuration.
    See https://portwing.codeswhat.com/docs/installation before starting it.
  EOS
end
