# This file was generated by GoReleaser. DO NOT EDIT.
cask "sockguard" do
  version "1.7.3"

  on_macos do
    on_intel do
      url "https://github.com/CodesWhat/sockguard/releases/download/v#{version}/sockguard_#{version}_darwin_amd64.tar.gz"
      sha256 "5fb3694a50e7046d10d172d35e6926d21c3f8a3e247d6750f4828c866ec74ced"
    end
    on_arm do
      url "https://github.com/CodesWhat/sockguard/releases/download/v#{version}/sockguard_#{version}_darwin_arm64.tar.gz"
      sha256 "ea1eb5cf0dd2ee7024c5de5ddb29e4a9bee3b3ab698f03011737ef5678a1b28b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/CodesWhat/sockguard/releases/download/v#{version}/sockguard_#{version}_linux_amd64.tar.gz"
      sha256 "b92a1b0fefe1933ba2472b60b92c9da01ce20fef97a21dbb7fd3e1be1c5da066"
    end
    on_arm do
      url "https://github.com/CodesWhat/sockguard/releases/download/v#{version}/sockguard_#{version}_linux_arm64.tar.gz"
      sha256 "ee6a1e09969c3603a429f55734624f315488bbccf3a8180595f9f2cfbfab10b1"
    end
  end

  name "sockguard"
  desc "Default-deny Docker socket proxy with request-aware policy enforcement"
  homepage "https://getsockguard.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sockguard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sockguard"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Sockguard needs access to a Docker socket and an explicit policy configuration.
    See https://getsockguard.com/docs/getting-started before starting it.
    The macOS binary is not yet Apple notarized. This cask removes its quarantine
    attribute after Homebrew verifies the release archive checksum.
  EOS
end
