# This file was generated by GoReleaser. DO NOT EDIT.
cask "sockguard" do
  version "2.2.1"

  on_macos do
    on_arm do
      sha256 "5683d6598c5d6a5462c79619c734fd087d1a8fba8e28fab4ff90410e14bf6964"
      url "https://github.com/CodesWhat/sockguard/releases/download/v#{version}/sockguard_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "70dbe0e796fd76c5253cf52359572817b17d9b3147c093510a207d77df88881c"
      url "https://github.com/CodesWhat/sockguard/releases/download/v#{version}/sockguard_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "35f2c2d18547f424fa7d75e5e4446fe54f77fb3998c179ec59edaa589e555ee7"
      url "https://github.com/CodesWhat/sockguard/releases/download/v#{version}/sockguard_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "083b26b328692fe0f9915c8d01eedda0e5dfa3586b661f844d94f7ba0aa8c80e"
      url "https://github.com/CodesWhat/sockguard/releases/download/v#{version}/sockguard_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sockguard"
  desc "Default-deny Docker socket proxy with request-aware policy enforcement"
  homepage "https://getsockguard.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sockguard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sockguard"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Sockguard needs access to a Docker socket and an explicit policy configuration.
    See https://getsockguard.com/docs/getting-started before starting it.
    The macOS binary is not yet Apple notarized. This cask removes its quarantine
    attribute after Homebrew verifies the release archive checksum.
  EOS
end
