# This file was generated by GoReleaser. DO NOT EDIT.
cask "sockguard" do
  version "2.2.0"

  on_macos do
    on_arm do
      sha256 "fae06ff13c19c7705ba3a61a43417a882d86895ce77b68a010ef16a3302b059c"
      url "https://github.com/CodesWhat/sockguard/releases/download/v#{version}/sockguard_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ac70ce17407757bed6fc08fa5cdcb3dadd460d042d006fbf48c658f463baf573"
      url "https://github.com/CodesWhat/sockguard/releases/download/v#{version}/sockguard_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "edb894ff19ee821f7be205e518d9fd3f4c9467d435335416090e87ad43d7ad64"
      url "https://github.com/CodesWhat/sockguard/releases/download/v#{version}/sockguard_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "44d1b95be70d400786c116dfab41cdfbf008d0a633ee54135bcae24a2cec66e8"
      url "https://github.com/CodesWhat/sockguard/releases/download/v#{version}/sockguard_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sockguard"
  desc "Default-deny Docker socket proxy with request-aware policy enforcement"
  homepage "https://getsockguard.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sockguard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sockguard"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Sockguard needs access to a Docker socket and an explicit policy configuration.
    See https://getsockguard.com/docs/getting-started before starting it.
    The macOS binary is not yet Apple notarized. This cask removes its quarantine
    attribute after Homebrew verifies the release archive checksum.
  EOS
end
