#!/usr/bin/env bash
#
# Runs `brew audit` over every cask in this tap, against the working tree
# rather than whatever copy of the tap Homebrew already has installed.
#
# Usage:
#   bash scripts/audit-casks.sh            # offline correctness checks
#   bash scripts/audit-casks.sh --online   # also verify every URL resolves
#
# The offline pass is fast and has no network dependency, so it is the gate on
# pull requests and pushes. The --online pass downloads from each url stanza to
# confirm it still resolves, which catches an upstream renaming or deleting a
# release asset out from under a cask; that runs on a schedule instead, because
# it is slow and can fail for reasons that have nothing to do with a change.
#
# `brew style` is deliberately NOT run here. It currently reports 18 stanza
# ordering and grouping offences, all of them in Casks/portwing.rb and
# Casks/sockguard.rb, which are generated by GoReleaser in their own projects
# and marked DO NOT EDIT. Gating on a rule this repository is not allowed to
# fix would mean a permanently red check. The fix belongs in those projects'
# GoReleaser cask templates.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

online=0
if [ "${1:-}" = "--online" ]; then
  online=1
  shift
fi
if [ "$#" -gt 0 ]; then
  echo "usage: $0 [--online]" >&2
  exit 2
fi

# Point Homebrew at this checkout, so the audit reads the casks as they exist
# here instead of the published tap. Symlinking is what Homebrew's own CI does.
tap_dir="$(brew --repository)/Library/Taps/codeswhat/homebrew-tap"
if [ -e "$tap_dir" ] && [ ! -L "$tap_dir" ]; then
  echo "note: $tap_dir is a real checkout, auditing that instead of this tree." >&2
elif [ ! -e "$tap_dir" ]; then
  mkdir -p "$(dirname "$tap_dir")"
  ln -s "$PWD" "$tap_dir"
fi

audit_args=(--cask)
if [ "$online" -eq 1 ]; then
  audit_args+=(--online)
fi

status=0
for cask in Casks/*.rb; do
  [ -e "$cask" ] || continue
  token="$(basename "$cask" .rb)"
  printf '=== %s ===\n' "$token"
  if brew audit "${audit_args[@]}" "codeswhat/tap/$token"; then
    printf 'ok     %s\n' "$token"
  else
    printf 'FAILED %s\n' "$token"
    status=1
  fi
done

exit "$status"
