#!/usr/bin/env bash
#
# Runs `brew audit` over every cask in this tap, against the working tree
# rather than whatever copy of the tap Homebrew already has installed.
#
# Usage:
#   bash scripts/audit-casks.sh            # offline correctness checks
#   bash scripts/audit-casks.sh --online   # also verify every URL resolves
#
# The offline pass is fast and has no network dependency, so it is the gate on
# pull requests and pushes. The --online pass downloads from each url stanza to
# confirm it still resolves, which catches an upstream renaming or deleting a
# release asset out from under a cask; that runs on a schedule instead, because
# it is slow and can fail for reasons that have nothing to do with a change.
#
# `brew style` is deliberately NOT run here. It currently reports 18 stanza
# ordering and grouping offences, all of them in Casks/portwing.rb and
# Casks/sockguard.rb, which are generated by GoReleaser in their own projects
# and marked DO NOT EDIT. Gating on a rule this repository is not allowed to
# fix would mean a permanently red check. The fix belongs in those projects'
# GoReleaser cask templates.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

online=0
if [ "${1:-}" = "--online" ]; then
  online=1
  shift
fi
if [ "$#" -gt 0 ]; then
  echo "usage: $0 [--online]" >&2
  exit 2
fi

# Point Homebrew at this checkout under a tap name of its own, never
# codeswhat/tap. If the real tap is already installed -- which it is on any
# machine that has run `brew install` from it -- reusing that name makes
# `brew audit` resolve the installed copy instead of the working tree, and
# report a green that says nothing about the changes being tested.
tap_dir="$(brew --repository)/Library/Taps/codeswhat-ci/homebrew-tap"
tap_name="codeswhat-ci/tap"
if [ -e "$tap_dir" ] || [ -L "$tap_dir" ]; then
  echo "ERROR  $tap_dir already exists; remove it and re-run." >&2
  exit 2
fi
mkdir -p "$(dirname "$tap_dir")"
ln -s "$PWD" "$tap_dir"
trap 'rm -f "$tap_dir"; rmdir "$(dirname "$tap_dir")" 2>/dev/null || true' EXIT

# --os/--arch because this tap carries both arm64-only casks and casks with
# separate on_intel and on_arm blocks. Left to itself brew audits only the
# runner's own architecture, so one of those two branches would never be read.
audit_args=(--cask --os=macos --arch=all)
if [ "$online" -eq 1 ]; then
  audit_args+=(--online)
fi

status=0
for cask in Casks/*.rb; do
  [ -e "$cask" ] || continue
  token="$(basename "$cask" .rb)"
  printf '=== %s ===\n' "$token"
  if brew audit "${audit_args[@]}" "$tap_name/$token"; then
    printf 'ok     %s\n' "$token"
  else
    printf 'FAILED %s\n' "$token"
    status=1
  fi
done

exit "$status"
